import { Recipe } from '@/lib/types';

export const sampleRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Classic Spaghetti Carbonara',
    description: 'A creamy Roman pasta dish made with eggs, cheese, pancetta, and black pepper.',
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    author: 'Chef Mario',
    createdAt: new Date('2026-01-01'),
    tags: ['Italian', 'Pasta', 'Quick'],
    ingredients: [
      {
        id: 'i1',
        name: 'spaghetti',
        amount: 400,
        unit: 'g',
        category: 'grain',
      },
      {
        id: 'i2',
        name: 'pancetta',
        amount: 200,
        unit: 'g',
        category: 'protein',
        substitutions: ['bacon', 'guanciale'],
      },
      {
        id: 'i3',
        name: 'eggs',
        amount: 4,
        unit: 'whole',
        category: 'protein',
        substitutions: ['egg substitute'],
      },
      {
        id: 'i4',
        name: 'Parmesan cheese',
        amount: 100,
        unit: 'g',
        category: 'dairy',
        substitutions: ['Pecorino Romano'],
      },
      {
        id: 'i5',
        name: 'black pepper',
        amount: 2,
        unit: 'tsp',
        category: 'spice',
      },
    ],
    instructions: [
      {
        id: 's1',
        step: 1,
        text: 'Bring a large pot of salted water to boil. Cook spaghetti according to package directions until al dente.',
        duration: 10,
      },
      {
        id: 's2',
        step: 2,
        text: 'While pasta cooks, cut pancetta into small cubes and fry in a large pan until crispy.',
        duration: 5,
      },
      {
        id: 's3',
        step: 3,
        text: 'Beat eggs in a bowl and mix in grated Parmesan cheese and black pepper.',
        duration: 2,
      },
      {
        id: 's4',
        step: 4,
        text: 'Reserve 1 cup pasta water. Drain pasta and add to pan with pancetta.',
        duration: 1,
      },
      {
        id: 's5',
        step: 5,
        text: 'Remove from heat. Quickly stir in egg mixture, adding pasta water as needed to create a creamy sauce.',
        duration: 2,
      },
    ],
  },
  {
    id: '2',
    title: 'Thai Green Curry',
    description: 'Aromatic and spicy Thai curry with coconut milk and fresh vegetables.',
    servings: 6,
    prepTime: 15,
    cookTime: 25,
    author: 'Chef Siri',
    createdAt: new Date('2026-01-03'),
    tags: ['Thai', 'Curry', 'Spicy', 'Vegetarian'],
    ingredients: [
      {
        id: 'i1',
        name: 'green curry paste',
        amount: 3,
        unit: 'tbsp',
        category: 'spice',
      },
      {
        id: 'i2',
        name: 'coconut milk',
        amount: 400,
        unit: 'ml',
        category: 'dairy',
        substitutions: ['coconut cream'],
      },
      {
        id: 'i3',
        name: 'bamboo shoots',
        amount: 200,
        unit: 'g',
        category: 'vegetable',
      },
      {
        id: 'i4',
        name: 'bell peppers',
        amount: 2,
        unit: 'whole',
        category: 'vegetable',
      },
      {
        id: 'i5',
        name: 'Thai basil',
        amount: 0.5,
        unit: 'cup',
        category: 'vegetable',
        substitutions: ['regular basil'],
      },
      {
        id: 'i6',
        name: 'tofu',
        amount: 400,
        unit: 'g',
        category: 'protein',
        substitutions: ['chicken', 'shrimp'],
      },
    ],
    instructions: [
      {
        id: 's1',
        step: 1,
        text: 'Heat a large pot over medium heat. Add curry paste and fry for 1 minute until fragrant.',
        duration: 2,
      },
      {
        id: 's2',
        step: 2,
        text: 'Add half the coconut milk and stir until combined with paste.',
        duration: 3,
      },
      {
        id: 's3',
        step: 3,
        text: 'Add tofu and cook for 5 minutes, then add vegetables and remaining coconut milk.',
        duration: 8,
      },
      {
        id: 's4',
        step: 4,
        text: 'Simmer for 10 minutes until vegetables are tender.',
        duration: 10,
      },
      {
        id: 's5',
        step: 5,
        text: 'Stir in Thai basil and serve over jasmine rice.',
        duration: 2,
      },
    ],
  },
];
